[project]
name = "shruti"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "fastapi[standard]>=0.128.0",
    "librosa>=0.11.0",
    "onnxruntime>=1.29.0",
    "python-dotenv>=1.2.1",
    "requests>=2.32.5",
    "silero-vad>=6.2.1",
    "soundfile>=0.13.1",
    "streamlit>=1.53.0",
    "streamlit-webrtc>=0.77.0",
    "torch>=2.9.1",
    "torchaudio>=2.11.0",
    "transformers>=4.57.6",
]
[tool.fastapi]
entrypoint = "app.main:app"
# this tells fastapi to load

[tool.uv.sources]
torch = { index = "pytorch-cpu" }
torchaudio = { index = "pytorch-cpu" }

[[tool.uv.index]]
name = "pytorch-cpu"
url = "https://download.pytorch.org/whl/cpu"
explicit = true

[dependency-groups]
dev = [
    "websockets>=16.0",
]
